/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/profiles/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["putProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fx/rates/{currency}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upsert"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/bulk-restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/bulk-categorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkCategorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restore_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/v1/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/v1/recurring/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch: operations["update_3"];
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch: operations["update_4"];
        trace?: never;
    };
    "/api/v1/budgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_5"];
        options?: never;
        head?: never;
        patch: operations["update_5"];
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_6"];
        trace?: never;
    };
    "/api/v1/transactions/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trash"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/trend-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trendComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["comparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/category-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categoryTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/cashflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cashflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["breakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["batches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fx/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/transactions/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["backup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/permanent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["permanent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteBatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthUser: {
            /** Format: int64 */
            id?: number;
            email?: string;
        };
        UpdateSettingsRequest: {
            reportingCurrency: string;
        };
        SettingsResponse: {
            reportingCurrency?: string;
        };
        ImportMapping: {
            delimiter?: string;
            encoding?: string;
            hasHeader?: boolean;
            /** Format: int32 */
            headerRowIndex?: number;
            /** Format: int32 */
            dateIndex?: number;
            dateFormat?: string;
            /** Format: int32 */
            descriptionIndex?: number;
            descriptionIndexes?: number[];
            /** @enum {string} */
            amountMode: "signed" | "debitCredit";
            /** Format: int32 */
            amountIndex?: number;
            expenseIsNegative?: boolean;
            /** Format: int32 */
            debitIndex?: number;
            /** Format: int32 */
            creditIndex?: number;
        };
        UpsertFxRateRequest: {
            rateToBase: number;
            source?: string;
        };
        FxRateResponse: {
            currency?: string;
            rateToBase?: number;
            baseCurrency?: string;
            stale?: boolean;
            source?: string;
            /** Format: date-time */
            lastFetchedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        CreateTransactionRequest: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            amountMinor: number;
            /** @enum {string} */
            type: "expense" | "income" | "transfer";
            /** Format: int64 */
            accountId: number;
            /** Format: int64 */
            counterAccountId?: number;
            /** Format: int64 */
            categoryId?: number;
            currency?: string;
            rateToBase?: number;
            description?: string;
            note?: string;
        };
        TransactionResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date */
            date?: string;
            /** Format: int64 */
            amountMinor?: number;
            /** @enum {string} */
            type?: "expense" | "income" | "transfer";
            /** Format: int64 */
            accountId?: number;
            /** Format: int64 */
            counterAccountId?: number;
            /** Format: int64 */
            categoryId?: number;
            currency?: string;
            rateToBase?: number;
            /** Format: int64 */
            baseMinor?: number;
            description?: string;
            note?: string;
            /** Format: int64 */
            importBatchId?: number;
            dedupeHash?: string;
            /** Format: int64 */
            version?: number;
        };
        BulkIdsRequest: {
            ids: number[];
        };
        BulkResult: {
            /** Format: int32 */
            affected?: number;
        };
        BulkCategorizeRequest: {
            ids: number[];
            /** Format: int64 */
            categoryId?: number;
        };
        CreateRuleRequest: {
            pattern: string;
            /** Format: int64 */
            categoryId: number;
            /** Format: int32 */
            priority?: number;
        };
        RuleResponse: {
            /** Format: int64 */
            id?: number;
            pattern?: string;
            /** Format: int64 */
            categoryId?: number;
            /** Format: int32 */
            priority?: number;
            /** Format: int64 */
            version?: number;
        };
        ApplyRulesResponse: {
            /** Format: int32 */
            scanned?: number;
            /** Format: int32 */
            categorized?: number;
        };
        CreateRecurringRequest: {
            /** Format: int64 */
            accountId: number;
            /** Format: int64 */
            amountMinor?: number;
            /** @enum {string} */
            type: "expense" | "income" | "transfer";
            /** Format: int64 */
            categoryId?: number;
            currency?: string;
            description?: string;
            note?: string;
            /** @enum {string} */
            frequency: "daily" | "weekly" | "monthly" | "yearly";
            /** Format: int32 */
            intervalCount?: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate?: string;
        };
        RecurringResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            accountId?: number;
            /** Format: int64 */
            categoryId?: number;
            /** Format: int64 */
            amountMinor?: number;
            /** @enum {string} */
            type?: "expense" | "income" | "transfer";
            currency?: string;
            description?: string;
            note?: string;
            /** @enum {string} */
            frequency?: "daily" | "weekly" | "monthly" | "yearly";
            /** Format: int32 */
            intervalCount?: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** Format: date */
            nextRunDate?: string;
            active?: boolean;
            /** Format: int64 */
            version?: number;
        };
        RunRecurringResponse: {
            /** Format: int32 */
            materialized?: number;
        };
        DetectionInfo: {
            encoding?: string;
            /** Format: int32 */
            headerRowIndex?: number;
            recognizedColumns?: {
                [key: string]: string;
            };
        };
        PreviewResponse: {
            delimiter?: string;
            misdecoded?: boolean;
            /** Format: int32 */
            totalRows?: number;
            /** Format: int32 */
            validRows?: number;
            /** Format: int32 */
            duplicateRows?: number;
            /** Format: int64 */
            incomeMinor?: number;
            /** Format: int64 */
            expenseMinor?: number;
            mapping?: components["schemas"]["ImportMapping"];
            detection?: components["schemas"]["DetectionInfo"];
            rows?: components["schemas"]["PreviewRow"][];
        };
        PreviewRow: {
            /** Format: int32 */
            index?: number;
            /** Format: date */
            date?: string;
            /** Format: int64 */
            amountMinor?: number;
            /** @enum {string} */
            type?: "expense" | "income" | "transfer";
            description?: string;
            valid?: boolean;
            error?: string;
            duplicate?: boolean;
        };
        CommitResponse: {
            /** Format: int64 */
            batchId?: number;
            /** Format: int32 */
            imported?: number;
            /** Format: int32 */
            skippedDuplicates?: number;
            /** Format: int32 */
            skippedInvalid?: number;
        };
        AccountBackup: {
            name?: string;
            type?: string;
            currency?: string;
            /** Format: int64 */
            startingBalanceMinor?: number;
            trackBalance?: boolean;
            archived?: boolean;
        };
        BackupResponse: {
            reportingCurrency?: string;
            accounts?: components["schemas"]["AccountBackup"][];
            categories?: components["schemas"]["CategoryBackup"][];
            transactions?: components["schemas"]["ExportedTransaction"][];
        };
        CategoryBackup: {
            name?: string;
            kind?: string;
            parent?: string;
            color?: string;
        };
        ExportedTransaction: {
            date?: string;
            type?: string;
            /** Format: int64 */
            amountMinor?: number;
            currency?: string;
            rateToBase?: number;
            account?: string;
            counterAccount?: string;
            category?: string;
            categoryParent?: string;
            description?: string;
            note?: string;
        };
        RestoreSummary: {
            /** Format: int32 */
            accountsCreated?: number;
            /** Format: int32 */
            categoriesCreated?: number;
            /** Format: int32 */
            transactionsImported?: number;
            /** Format: int32 */
            transactionsSkipped?: number;
            /** Format: int32 */
            transfersSkipped?: number;
        };
        CreateCategoryRequest: {
            name: string;
            /** @enum {string} */
            kind: "expense" | "income";
            /** Format: int64 */
            parentId?: number;
            color?: string;
        };
        CategoryResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            kind?: "expense" | "income";
            /** Format: int64 */
            parentId?: number;
            color?: string;
            /** Format: int64 */
            version?: number;
        };
        CreateBudgetRequest: {
            /** Format: int64 */
            categoryId: number;
            /** Format: int64 */
            amountMinor?: number;
            rollover?: boolean;
        };
        BudgetResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            categoryId?: number;
            /** Format: int64 */
            amountMinor?: number;
            /** Format: int64 */
            version?: number;
            rollover?: boolean;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName?: string;
        };
        TokenResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
            user?: components["schemas"]["UserProfileResponse"];
        };
        UserProfileResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            displayName?: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        CreateAccountRequest: {
            name: string;
            /** @enum {string} */
            type: "checking" | "savings" | "cash" | "credit";
            currency: string;
            trackBalance?: boolean;
            /** Format: int64 */
            startingBalanceMinor?: number;
        };
        AccountResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            type?: "checking" | "savings" | "cash" | "credit";
            currency?: string;
            /** Format: int64 */
            startingBalanceMinor?: number;
            trackBalance?: boolean;
            archived?: boolean;
            /** Format: int64 */
            version?: number;
        };
        UpdateTransactionRequest: {
            /** Format: int64 */
            version: number;
            /** Format: date */
            date?: string;
            /** Format: int64 */
            amountMinor?: number;
            /** Format: int64 */
            categoryId?: number;
            description?: string;
            note?: string;
        };
        UpdateRuleRequest: {
            /** Format: int64 */
            version: number;
            pattern?: string;
            /** Format: int64 */
            categoryId?: number;
            /** Format: int32 */
            priority?: number;
        };
        UpdateRecurringRequest: {
            /** Format: int64 */
            version: number;
            /** Format: int64 */
            amountMinor?: number;
            description?: string;
            note?: string;
            active?: boolean;
            /** Format: date */
            endDate?: string;
        };
        UpdateCategoryRequest: {
            /** Format: int64 */
            version: number;
            name?: string;
            color?: string;
        };
        UpdateBudgetRequest: {
            /** Format: int64 */
            amountMinor?: number;
            /** Format: int64 */
            version?: number;
            rollover?: boolean;
        };
        UpdateAccountRequest: {
            /** Format: int64 */
            version: number;
            name?: string;
            /** @enum {string} */
            type?: "checking" | "savings" | "cash" | "credit";
            trackBalance?: boolean;
            /** Format: int64 */
            startingBalanceMinor?: number;
        };
        PageResponseTransactionResponse: {
            items?: components["schemas"]["TransactionResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
        TrendBucket: {
            period?: string;
            /** Format: int64 */
            incomeMinor?: number;
            /** Format: int64 */
            expenseMinor?: number;
        };
        TrendResponse: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            interval?: string;
            currency?: string;
            buckets?: components["schemas"]["TrendBucket"][];
        };
        CategoryMover: {
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            color?: string;
            /** Format: int64 */
            currentMinor?: number;
            /** Format: int64 */
            previousMinor?: number;
            /** Format: int64 */
            deltaMinor?: number;
        };
        Delta: {
            /** Format: int64 */
            incomeMinor?: number;
            /** Format: int64 */
            expenseMinor?: number;
            /** Format: int64 */
            netMinor?: number;
        };
        PeriodSummary: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            /** Format: int64 */
            incomeMinor?: number;
            /** Format: int64 */
            expenseMinor?: number;
            /** Format: int64 */
            netMinor?: number;
        };
        TrendComparisonResponse: {
            currency?: string;
            current?: components["schemas"]["PeriodSummary"];
            previous?: components["schemas"]["PeriodSummary"];
            delta?: components["schemas"]["Delta"];
            movers?: components["schemas"]["CategoryMover"][];
        };
        SummaryResponse: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            currency?: string;
            /** Format: int64 */
            incomeMinor?: number;
            /** Format: int64 */
            expenseMinor?: number;
            /** Format: int64 */
            netMinor?: number;
        };
        ComparisonResponse: {
            currency?: string;
            mode?: string;
            current?: components["schemas"]["PeriodSummary"];
            previous?: components["schemas"]["PeriodSummary"];
            delta?: components["schemas"]["Delta"];
        };
        CategorySeries: {
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            color?: string;
        };
        CategoryTrendBucket: {
            period?: string;
            amounts?: {
                [key: string]: number;
            };
        };
        CategoryTrendResponse: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            interval?: string;
            currency?: string;
            /** @enum {string} */
            kind?: "expense" | "income";
            series?: components["schemas"]["CategorySeries"][];
            buckets?: components["schemas"]["CategoryTrendBucket"][];
        };
        CashflowBucket: {
            period?: string;
            /** Format: int64 */
            incomeMinor?: number;
            /** Format: int64 */
            expenseMinor?: number;
            /** Format: int64 */
            netMinor?: number;
            /** Format: int64 */
            runningNetMinor?: number;
        };
        CashflowResponse: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            interval?: string;
            currency?: string;
            buckets?: components["schemas"]["CashflowBucket"][];
        };
        BreakdownChild: {
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            /** Format: int64 */
            baseMinor?: number;
            /** Format: double */
            share?: number;
        };
        BreakdownParent: {
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            color?: string;
            /** Format: int64 */
            baseMinor?: number;
            /** Format: double */
            share?: number;
            children?: components["schemas"]["BreakdownChild"][];
        };
        BreakdownResponse: {
            /** @enum {string} */
            kind?: "expense" | "income";
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            currency?: string;
            /** Format: int64 */
            totalBaseMinor?: number;
            /** Format: int64 */
            count?: number;
            parents?: components["schemas"]["BreakdownParent"][];
        };
        ImportBatchResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            accountId?: number;
            fileName?: string;
            /** Format: int32 */
            count?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        FxRatesResponse: {
            baseCurrency?: string;
            rates?: components["schemas"]["FxRateResponse"][];
        };
        BudgetProgress: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            categoryId?: number;
            categoryName?: string;
            color?: string;
            /** Format: int64 */
            amountMinor?: number;
            /** Format: int64 */
            spentMinor?: number;
            /** Format: int64 */
            remainingMinor?: number;
            over?: boolean;
            /** Format: int64 */
            version?: number;
            rollover?: boolean;
            /** Format: int64 */
            carriedInMinor?: number;
        };
        BudgetsResponse: {
            month?: string;
            currency?: string;
            items?: components["schemas"]["BudgetProgress"][];
        };
        AccountBalanceResponse: {
            /** Format: int64 */
            accountId?: number;
            currency?: string;
            /** Format: int64 */
            balanceMinor?: number;
        };
        DeleteCategoryResponse: {
            /** Format: int64 */
            uncategorizedTransactions?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportMapping"];
                };
            };
        };
    };
    putProfile: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportMapping"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportMapping"];
                };
            };
        };
    };
    upsert: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                currency: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertFxRateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FxRateResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                currency: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from?: string;
                to?: string;
                accountId?: number;
                type?: "expense" | "income" | "transfer";
                categoryId?: number;
                q?: string;
                sort?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseTransactionResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
        };
    };
    restore: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
        };
    };
    bulkRestore: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkIdsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkResult"];
                };
            };
        };
    };
    bulkDelete: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkIdsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkResult"];
                };
            };
        };
    };
    bulkCategorize: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCategorizeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkResult"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleResponse"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplyRulesResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecurringResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecurringResponse"];
                };
            };
        };
    };
    run: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunRecurringResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query: {
                accountId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    user?: components["schemas"]["AuthUser"];
                    /** Format: binary */
                    file: string;
                    mapping?: components["schemas"]["ImportMapping"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PreviewResponse"];
                };
            };
        };
    };
    commit: {
        parameters: {
            query: {
                accountId: number;
            };
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    user?: components["schemas"]["AuthUser"];
                    /** Format: binary */
                    file: string;
                    mapping?: components["schemas"]["ImportMapping"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommitResponse"];
                };
            };
        };
    };
    restore_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackupResponse"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestoreSummary"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                kind?: "expense" | "income";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BudgetsResponse"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBudgetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BudgetResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"][];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecurringResponse"];
                };
            };
        };
    };
    delete_4: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeleteCategoryResponse"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    delete_5: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_5: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBudgetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BudgetResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    update_6: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    trash: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseTransactionResponse"];
                };
            };
        };
    };
    trend: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from: string;
                to: string;
                interval?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrendResponse"];
                };
            };
        };
    };
    trendComparison: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrendComparisonResponse"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SummaryResponse"];
                };
            };
        };
    };
    comparison: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from: string;
                to: string;
                mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComparisonResponse"];
                };
            };
        };
    };
    categoryTrend: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from: string;
                to: string;
                interval?: string;
                kind?: "expense" | "income";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTrendResponse"];
                };
            };
        };
    };
    cashflow: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from: string;
                to: string;
                interval?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CashflowResponse"];
                };
            };
        };
    };
    breakdown: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from: string;
                to: string;
                kind?: "expense" | "income";
                parentId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BreakdownResponse"];
                };
            };
        };
    };
    batches: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportBatchResponse"][];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FxRatesResponse"];
                };
            };
        };
    };
    json: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExportedTransaction"][];
                };
            };
        };
    };
    csv: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    backup: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BackupResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    balance: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountBalanceResponse"];
                };
            };
        };
    };
    permanent: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteBatch: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
