/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/profiles/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["putProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fx/rates/{currency}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upsert"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/v1/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch: operations["update_3"];
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_4"];
        trace?: never;
    };
    "/api/v1/reports/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["breakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["batches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fx/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteBatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthUser: {
            /** Format: int64 */
            id?: number;
            email?: string;
        };
        UpdateSettingsRequest: {
            reportingCurrency: string;
        };
        SettingsResponse: {
            reportingCurrency?: string;
        };
        ImportMapping: {
            delimiter?: string;
            encoding?: string;
            hasHeader?: boolean;
            /** Format: int32 */
            dateIndex?: number;
            dateFormat?: string;
            /** Format: int32 */
            descriptionIndex?: number;
            /** @enum {string} */
            amountMode: "signed" | "debitCredit";
            /** Format: int32 */
            amountIndex?: number;
            expenseIsNegative?: boolean;
            /** Format: int32 */
            debitIndex?: number;
            /** Format: int32 */
            creditIndex?: number;
        };
        UpsertFxRateRequest: {
            rateToBase: number;
            source?: string;
        };
        FxRateResponse: {
            currency?: string;
            rateToBase?: number;
            baseCurrency?: string;
            stale?: boolean;
            source?: string;
            /** Format: date-time */
            lastFetchedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        CreateTransactionRequest: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            amountMinor: number;
            /** @enum {string} */
            type: "expense" | "income" | "transfer";
            /** Format: int64 */
            accountId: number;
            /** Format: int64 */
            counterAccountId?: number;
            /** Format: int64 */
            categoryId?: number;
            currency?: string;
            rateToBase?: number;
            description?: string;
            note?: string;
        };
        TransactionResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date */
            date?: string;
            /** Format: int64 */
            amountMinor?: number;
            /** @enum {string} */
            type?: "expense" | "income" | "transfer";
            /** Format: int64 */
            accountId?: number;
            /** Format: int64 */
            counterAccountId?: number;
            /** Format: int64 */
            categoryId?: number;
            currency?: string;
            rateToBase?: number;
            /** Format: int64 */
            baseMinor?: number;
            description?: string;
            note?: string;
            /** Format: int64 */
            importBatchId?: number;
            dedupeHash?: string;
            /** Format: int64 */
            version?: number;
        };
        CreateRuleRequest: {
            pattern: string;
            /** Format: int64 */
            categoryId: number;
            /** Format: int32 */
            priority?: number;
        };
        RuleResponse: {
            /** Format: int64 */
            id?: number;
            pattern?: string;
            /** Format: int64 */
            categoryId?: number;
            /** Format: int32 */
            priority?: number;
            /** Format: int64 */
            version?: number;
        };
        ApplyRulesResponse: {
            /** Format: int32 */
            scanned?: number;
            /** Format: int32 */
            categorized?: number;
        };
        PreviewResponse: {
            delimiter?: string;
            misdecoded?: boolean;
            /** Format: int32 */
            totalRows?: number;
            /** Format: int32 */
            validRows?: number;
            /** Format: int32 */
            duplicateRows?: number;
            rows?: components["schemas"]["PreviewRow"][];
        };
        PreviewRow: {
            /** Format: int32 */
            index?: number;
            /** Format: date */
            date?: string;
            /** Format: int64 */
            amountMinor?: number;
            /** @enum {string} */
            type?: "expense" | "income" | "transfer";
            description?: string;
            valid?: boolean;
            error?: string;
            duplicate?: boolean;
        };
        CommitResponse: {
            /** Format: int64 */
            batchId?: number;
            /** Format: int32 */
            imported?: number;
            /** Format: int32 */
            skippedDuplicates?: number;
            /** Format: int32 */
            skippedInvalid?: number;
        };
        CreateCategoryRequest: {
            name: string;
            /** @enum {string} */
            kind: "expense" | "income";
            /** Format: int64 */
            parentId?: number;
            color?: string;
        };
        CategoryResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            kind?: "expense" | "income";
            /** Format: int64 */
            parentId?: number;
            color?: string;
            /** Format: int64 */
            version?: number;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName?: string;
        };
        TokenResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
            user?: components["schemas"]["UserProfileResponse"];
        };
        UserProfileResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            displayName?: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        CreateAccountRequest: {
            name: string;
            /** @enum {string} */
            type: "checking" | "savings" | "cash" | "credit";
            currency: string;
            trackBalance?: boolean;
            /** Format: int64 */
            startingBalanceMinor?: number;
        };
        AccountResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            type?: "checking" | "savings" | "cash" | "credit";
            currency?: string;
            /** Format: int64 */
            startingBalanceMinor?: number;
            trackBalance?: boolean;
            archived?: boolean;
            /** Format: int64 */
            version?: number;
        };
        UpdateTransactionRequest: {
            /** Format: int64 */
            version: number;
            /** Format: date */
            date?: string;
            /** Format: int64 */
            amountMinor?: number;
            /** Format: int64 */
            categoryId?: number;
            description?: string;
            note?: string;
        };
        UpdateRuleRequest: {
            /** Format: int64 */
            version: number;
            pattern?: string;
            /** Format: int64 */
            categoryId?: number;
            /** Format: int32 */
            priority?: number;
        };
        UpdateCategoryRequest: {
            /** Format: int64 */
            version: number;
            name?: string;
            color?: string;
        };
        UpdateAccountRequest: {
            /** Format: int64 */
            version: number;
            name?: string;
            /** @enum {string} */
            type?: "checking" | "savings" | "cash" | "credit";
            trackBalance?: boolean;
            /** Format: int64 */
            startingBalanceMinor?: number;
        };
        PageResponseTransactionResponse: {
            items?: components["schemas"]["TransactionResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
        SummaryResponse: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            currency?: string;
            /** Format: int64 */
            incomeMinor?: number;
            /** Format: int64 */
            expenseMinor?: number;
            /** Format: int64 */
            netMinor?: number;
        };
        BreakdownChild: {
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            /** Format: int64 */
            baseMinor?: number;
            /** Format: double */
            share?: number;
        };
        BreakdownParent: {
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            color?: string;
            /** Format: int64 */
            baseMinor?: number;
            /** Format: double */
            share?: number;
            children?: components["schemas"]["BreakdownChild"][];
        };
        BreakdownResponse: {
            /** @enum {string} */
            kind?: "expense" | "income";
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            currency?: string;
            /** Format: int64 */
            totalBaseMinor?: number;
            /** Format: int64 */
            count?: number;
            parents?: components["schemas"]["BreakdownParent"][];
        };
        ImportBatchResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            accountId?: number;
            fileName?: string;
            /** Format: int32 */
            count?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        FxRatesResponse: {
            baseCurrency?: string;
            rates?: components["schemas"]["FxRateResponse"][];
        };
        AccountBalanceResponse: {
            /** Format: int64 */
            accountId?: number;
            currency?: string;
            /** Format: int64 */
            balanceMinor?: number;
        };
        DeleteCategoryResponse: {
            /** Format: int64 */
            uncategorizedTransactions?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportMapping"];
                };
            };
        };
    };
    putProfile: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportMapping"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportMapping"];
                };
            };
        };
    };
    upsert: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                currency: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertFxRateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FxRateResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                currency: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from?: string;
                to?: string;
                accountId?: number;
                type?: "expense" | "income" | "transfer";
                categoryId?: number;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseTransactionResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleResponse"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplyRulesResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query: {
                accountId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    user?: components["schemas"]["AuthUser"];
                    /** Format: binary */
                    file: string;
                    mapping: components["schemas"]["ImportMapping"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PreviewResponse"];
                };
            };
        };
    };
    commit: {
        parameters: {
            query: {
                accountId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    user?: components["schemas"]["AuthUser"];
                    /** Format: binary */
                    file: string;
                    mapping: components["schemas"]["ImportMapping"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommitResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                kind?: "expense" | "income";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeleteCategoryResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SummaryResponse"];
                };
            };
        };
    };
    breakdown: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
                from: string;
                to: string;
                kind?: "expense" | "income";
                parentId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BreakdownResponse"];
                };
            };
        };
    };
    batches: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportBatchResponse"][];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FxRatesResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    balance: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountBalanceResponse"];
                };
            };
        };
    };
    deleteBatch: {
        parameters: {
            query: {
                user: components["schemas"]["AuthUser"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
